### PR TITLE
Improvements #2

### PR DESCRIPTION
**Pull request by JarnoBoks**
(Sorry, previous pull request contained my previous fixes, without your changes) 

Proposal for changes in installation on Tomato Router (changed Makefile to minify & secure). Added yuicompressor for minification (needs Java installed on Linux build system, check the README.

Secondly fixed issue 88 (sorting on the qos-classify page) and changed the editorRow to display correct.

Question: yuicompressor cannot minify asp files. I would like to cut out the javascript from the asp pages and move it to a separate file (ie. js/qos-classify.js). What do you think?

### CODE REVIEW

**Comment by Jackysi** [comment]
I would write this to previous pull request but I forgot, if you could stop adding comments like 
```javascript
# Ratatosk: Obsolete for js files because of usage of yuicompressor, but not removed yet.
```
That would be greatly appreciated. I do want to give you credit, even when merging requests your name and Github URL is seen, so there is no need to add these things into comments. When I have to modify the patches I actually drop chain of commits. 

I will merge this request soon. Thanks for another awesome update!

**Comment by JarnoBoks** [comment]
The comments are not meant for credits, but for my own reference ;) But I'll remove them in future pull request. 

I missed the keyframes bug from YUI compressor, sorry. But it is easily fixed using 0.00% or even better the from..to keywords. Are there any more issues?

**Comment by Jackysi** [comment]
I never used from/to syntax so need to give it a try. At this time I didn't find any additional issues. I am only a bit let down by the fact that YUI Compressor is not updated any more (version 2.48 comes from 2013) but it works!

**Comment by JarnoBoks** [comment]
As far for the from and to keywords: http://www.w3schools.com/cssref/css3_pr_animation-keyframes.asp. It's a small fix for a 100Kb smaller codebase ;) 

Yui 2.4.9 is in development, but the developer is a litte bit disappointed in the community it seams ;)

P.S. No problem

**Pull request closed without merging**
