### PR TITLE
Fixes upstream

### PR DESCRIPTION
**Pull request by JarnoBoks**
Proposal for changes in installation on Tomato Router (changed Makefile to minify & secure). Added yuicompressor for minification (needs Java installed on Linux build system, check the README.

Secondly fixed issue 88 (sorting on the qos-classify page) and changed the editorRow to display correct.

Question: yuicompressor cannot minify asp files. I would like to cut out the javascript from the asp pages and move it to a separate file (ie. js/qos-classify.js). What do you think?

### CODE REVIEW

**Comment by Jackysi** [comment]
The files are already minified by tomato make file. The problem is only that the make file doesn't work in sub directories (like css/js/img). However I wonder why you closed this pull request?

**Comment by JarnoBoks** [comment]
Hi Jacky,

 

They are, but the makefile doesn’t do this as thorough as yuicompressor does (fe yuicompressor shortens variable names too and removes single line comments, ie starting with //). The makefile changes I proposed ensure the files in css and js folders are minified too. 

 

I closed the pull request because I saw the previous fixes were included again (I aint a git guru;) ) But if the merging it isn’t a problem for you, it can be reopened.

 

Grtz,

Jarno

 

 

Van: Jacky Prahec [mailto:notifications@github.com] 
Verzonden: maandag 28 december 2015 10:20
Aan: Jackysi/advancedtomato-gui
CC: JarnoBoks
Onderwerp: Re: [advancedtomato-gui] Fixes upstream (#14)

 

The files are already minified by tomato make file. The problem is only that the make file doesn't work in sub directories (like css/js/img). However I wonder why you closed this pull request?

**Comment by Jackysi** [comment]
I agree, YUI is better in that way, its limited to JS/CSS though. Did you actually test it with compilation? 
Merge would be best and easiest choice for you I guess, since you are so kind to contribute I will attempt to do it manually. Thanks for your contribution :)

**Comment by JarnoBoks** [comment]
I’ve opened a new pull request yesterday, that should be mergable I think.

Yes, I’ve tried to compile and it functions (if you have java installed on the build system).

 

I know it is limited to JS/CSS and that is why I proposed to split the files, however this could be an issue for you in merging future shibby changes. So before I split the files, I’d like to know if you fancy that.

**Comment by Jackysi** [comment]
Wait why would you split them? I like it to work on top of other optimizations, that's great.

**Pull request closed without merging**
